const state={serverAvailable:false,connected:false,roomId:"",roomUrl:"",roomTitle:"待连接直播间",sessionId:null,runId:null,generation:0,workerAlive:false,dataSource:"none",asOf:null,lastValidAt:null,freshness:null,coverage:{coverage_state:"unknown"},status:"idle",mode:"auto",filter:"all",search:"",events:[],metrics:null,lastError:""};
let capabilityToken="";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const typeNames={comment:"评论",like:"点赞",gift:"礼物",follow:"关注",share:"分享",viewer_change:"在线人数",entry:"进场",live_status:"状态"};
const snapshotApi=BulletScreenSnapshot;
const formatNumber=n=>n===null||n===undefined||Number.isNaN(Number(n))?"—":new Intl.NumberFormat("zh-CN",{maximumFractionDigits:1}).format(n);
const percent=n=>n===null||n===undefined||Number.isNaN(Number(n))?"—":`${Math.round(Number(n)*100)}%`;
const escapeHtml=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");

function backendEventToFeed(item){const stamp=String(item.timestamp||item.event_time||"");const parsed=new Date(stamp);const time=Number.isNaN(parsed.getTime())?(stamp.slice(11,19)||"--:--:--"):parsed.toLocaleTimeString("zh-CN",{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"});return {time,user:item.user?.name||item.user_name||"匿名用户",type:item.type||item.event_type||"live_status",text:item.content||item.text||"",topic:item.topic||""};}
function currentWindow(){const selected=$("#rangeSelect")?.value||"60s";return state.metrics?.windows?.[selected]||state.metrics?.current||{};}
function renderFeed(){const list=$("#feedList"),query=state.search.toLowerCase();const filtered=state.events.filter(item=>(state.filter==="all"||item.type===state.filter)&&(!query||`${item.user} ${item.text}`.toLowerCase().includes(query)));list.innerHTML=filtered.length?filtered.slice(-160).reverse().map(item=>`<div class="feed-item"><span class="feed-time">[${escapeHtml(item.time)}]</span><div class="feed-main"><span class="feed-type ${escapeHtml(item.type)}">${escapeHtml(typeNames[item.type]||item.type)}</span><span class="feed-user">${escapeHtml(item.user)}：</span><span class="feed-text">${escapeHtml(item.text||"—")}</span></div></div>`).join(""):`<div class="empty-feed">没有匹配的事件<br><small>等待连接后的 protobuf 实时事件</small></div>`;$("#allCount").textContent=state.events.length;$("#eventRate").textContent=state.metrics?`${formatNumber(currentWindow().comment_rate)} 评论事件/分`:"—";}
function renderMetrics(){const current=currentWindow();const sentiment=state.metrics?.summary?.sentiment||{};const protocol=!!state.metrics?.diagnostics?.protocol_verified;const online=current.online??state.metrics?.online;$("#metricOnline").textContent=state.connected&&online!==null&&online!==undefined?`${protocol?"":"≈ "}${formatNumber(online)}`:"—";$("#metricCommentRate").textContent=state.connected?formatNumber(current.comment_rate):"—";$("#metricLikeRate").textContent=state.connected?formatNumber(current.like_rate):"—";$("#metricActive").textContent=state.connected?formatNumber(current.active_users):"—";$("#metricPurchase").textContent=state.connected?percent(current.purchase_ratio):"—";$("#metricSentiment").textContent=state.connected?`${percent(sentiment.positive)} / ${percent(sentiment.negative)}`:"—";$("#trendValue").innerHTML=state.connected?`${formatNumber(current.heat_score)} <small>观测热度</small>`:`— <small>等待连接</small>`;}
function renderAnalysis(){const metrics=state.metrics||{};const topics=metrics.topics||[];const questions=metrics.hot_questions||[];$("#topicList").innerHTML=topics.length?topics.map(item=>`<span class="analysis-chip">${escapeHtml(item.label)} <b>${item.count}</b></span>`).join(""):`<span class="muted">连接后生成</span>`;$("#questionList").innerHTML=questions.length?questions.map(item=>`<div class="question-row"><span>${escapeHtml(item.question)}</span><b>${item.count}</b></div>`).join(""):`<div class="muted">等待评论事件</div>`;const sentiment=metrics.summary?.sentiment||{};const positive=sentiment.positive===null||sentiment.positive===undefined||Number.isNaN(Number(sentiment.positive))?null:Number(sentiment.positive),negative=sentiment.negative===null||sentiment.negative===undefined||Number.isNaN(Number(sentiment.negative))?null:Number(sentiment.negative),neutral=positive===null||negative===null?null:Math.max(0,1-positive-negative);$("#positiveBar").style.width=positive===null?"0%":`${positive*100}%`;$("#neutralBar").style.width=neutral===null?"0%":`${neutral*100}%`;$("#negativeBar").style.width=negative===null?"0%":`${negative*100}%`;$("#sentimentLabel").textContent=state.connected?(positive===null||negative===null?"正 — · 中 — · 负 —":`正 ${percent(positive)} · 中 ${percent(neutral)} · 负 ${percent(negative)}`):"—";}
function renderSignals(){const signals=state.metrics?.signals||[];$("#signalCount").textContent=signals.length?`${signals.length} 条`:"—";$("#signalList").innerHTML=signals.length?signals.map(BulletScreenSignals.renderCard).join(""):`<div class="empty-state"><span class="empty-orb">◎</span><p>当前没有可确认的规则信号</p><small>采集证据不足或样本未达到门槛时不会猜测结论</small></div>`;}
function renderKeywords(){const metrics=state.metrics||{},keywords=metrics.keywords||[];const max=Math.max(...keywords.map(item=>Number(item[1])||0),1);$("#keywordList").innerHTML=keywords.length?keywords.map(item=>`<div class="keyword-row" style="--bar:${Math.max(15,(Number(item[1])||0)/max*100)}%"><span>${escapeHtml(item[0])}</span><span class="keyword-count">${item[1]}</span></div>`).join(""):`<div class="empty-feed">连接后显示评论热词</div>`;const current=currentWindow();$("#miniStats").innerHTML=`<span>礼物事件 / 分 <b>${formatNumber(current.gift_rate)}</b></span><span>分享事件 / 分 <b>${formatNumber((current.shares||0)*1)}</b></span><span>观测热度 <b>${formatNumber(current.heat_score)}</b></span>`;$("#windowLabel").textContent=$("#rangeSelect").value==="10s"?"10 秒":$("#rangeSelect").value==="5m"?"5 分钟":"60 秒";}
function createPath(points,width,height,padding=22){const known=points.map((point,index)=>[point,index]).filter(([point])=>Number.isFinite(point));if(known.length<2)return "";const max=Math.max(...known.map(item=>item[0])),min=Math.min(...known.map(item=>item[0])),range=max-min||1;return known.map(([point,index],pathIndex)=>{const x=padding+index*((width-padding*2)/(points.length-1));const y=height-padding-((point-min)/range)*(height-padding*2);return `${pathIndex?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`;}).join(" ");}
function renderChart(){const svg=$("#trendChart"),points=state.metrics?.trend||[],width=720,height=210,grid=[35,75,115,155,195].map(y=>`<line class="chart-gridline" x1="22" y1="${y}" x2="698" y2="${y}"/>`).join("");if(points.length<2){svg.innerHTML=`${grid}<text x="360" y="112" text-anchor="middle" fill="#9095a1" font-size="12">连接后生成真实趋势</text>`;$("#chartAxis").innerHTML="<span>—</span><span>—</span><span>—</span><span>等待数据</span>";return;}const online=points.map(point=>point.online===null||point.online===undefined?null:Number(point.online)),comments=points.map(point=>point.comment_rate===null||point.comment_rate===undefined||Number.isNaN(Number(point.comment_rate))?null:Number(point.comment_rate)),onlinePath=createPath(online,width,height),commentPath=createPath(comments,width,height),areaPath=onlinePath?`${onlinePath} L698,${height-10} L22,${height-10} Z`:"";svg.innerHTML=`<defs><linearGradient id="trendFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#4c9ae8" stop-opacity=".28"/><stop offset="1" stop-color="#4c9ae8" stop-opacity=".03"/></linearGradient></defs>${grid}${areaPath?`<path class="chart-area" d="${areaPath}"/>`:""}${onlinePath?`<path class="chart-online" d="${onlinePath}"/>`:""}${commentPath?`<path class="chart-danmaku" d="${commentPath}"/>`:""}`;const times=points.map(point=>String(point.recorded_at||"").slice(11,16)||"—");$("#chartAxis").innerHTML=[times[0],times[Math.floor(times.length/2)],times[times.length-1],"现在"].map(label=>`<span>${escapeHtml(label)}</span>`).join("");}
function renderConnection(){const status=state.serverAvailable?state.status:"offline";const protocol=!!state.metrics?.diagnostics?.protocol_verified;$("#roomIdLabel").textContent=state.roomId?`# ${state.roomId}`:"—";$("#roomTitle").textContent=state.roomTitle;$("#modeBadge").textContent=state.mode==="demo"?"演示模式":protocol?"PROTOBUF 实时":state.serverAvailable?"浏览器连接":"服务离线";$("#connectButton").classList.toggle("connected",state.connected);$("#connectButton").classList.toggle("disconnected",!state.connected);$("#connectLabel").textContent=snapshotApi.statusText(status);$("#feedState").classList.toggle("paused",!state.connected);$("#feedState").innerHTML=`<span class="pulse-dot"></span>${snapshotApi.statusText(status)}`;const identity=state.sessionId?`会话 ${state.sessionId} · run ${String(state.runId||"").slice(0,8)} · 第 ${state.generation} 代`:`暂无当前会话`;$("#feedFooterText").textContent=state.lastError?`${snapshotApi.statusText(status)}：${state.lastError}`:`${identity} · ${snapshotApi.coverageText(state.coverage)}`;$("#feedFooterText").title=state.asOf?`数据截至 ${state.asOf}`:"";$("#dashboardFootText").textContent=state.lastError||`数据源：${state.dataSource} · 时间截至 ${state.asOf||"—"}`;}
function renderAll(){renderConnection();renderFeed();renderMetrics();renderAnalysis();renderSignals();renderKeywords();renderChart();}
async function loadCapability(){const response=await fetch("/api/bootstrap",{headers:{"Accept":"application/json"}});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.token)throw new Error(payload.error||"本地服务未提供会话令牌");capabilityToken=payload.token;return capabilityToken;}
async function apiJson(path,options={},retry=true){if(path!=="/api/bootstrap"&&!capabilityToken)await loadCapability();const headers={"Content-Type":"application/json",...(options.headers||{}),...(capabilityToken?{"X-Bullet-Screen-Token":capabilityToken}:{})};const response=await fetch(path,{...options,headers});const payload=await response.json().catch(()=>({}));if(response.status===401&&retry){capabilityToken="";await loadCapability();return apiJson(path,options,false);}if(!response.ok)throw new Error(payload.error||`本地服务 HTTP ${response.status}`);return payload;}
let snapshotClient;
snapshotClient=new snapshotApi.SnapshotClient(({signal,requestGeneration})=>{const window=$("#rangeSelect")?.value||"60s";return apiJson(`/api/snapshot?window=${encodeURIComponent(window)}&limit=300`,{signal,headers:{"X-Bullet-Screen-Request-Generation":String(requestGeneration)}});},snapshot=>{const next=snapshotApi.applySnapshotState(state,snapshot),metrics=snapshot.metrics||{};Object.assign(state,next,{serverAvailable:true,status:snapshot.status||"idle",roomUrl:state.roomUrl,mode:metrics.adapter_mode||state.mode,events:(snapshot.events?.items||[]).map(backendEventToFeed)});renderAll();$("#snapshotLabel").textContent=`${snapshotApi.statusText(state.status)} · ${snapshotApi.coverageText(state.coverage)} · ${state.asOf?new Date(state.asOf).toLocaleTimeString("zh-CN",{hour12:false}):"—"}`;},error=>{const wasAvailable=state.serverAvailable;Object.assign(state,snapshotApi.clearSnapshotState(state,error.message),{serverAvailable:wasAvailable,status:wasAvailable?"error":"offline",dataSource:"none"});if(wasAvailable)showToast(`本地服务异常：${error.message}`);renderAll();});
async function syncBackend(){return snapshotClient.refresh();}
async function connectBackend(){try{if(!state.serverAvailable)await syncBackend();if(!state.serverAvailable){showToast("本地服务未启动：请运行 python3 server.py");return;}if(state.connected){await apiJson("/api/disconnect",{method:"POST",body:"{}"});}else{const input=$("#roomInput").value.trim();if(!input){showToast("请填写抖音 URL 或 room_id");openSettings();return;}const isId=/^\d+$/.test(input);await apiJson("/api/connect",{method:"POST",body:JSON.stringify({room_id:isId?input:"",url:isId?"":input,cookie:$("#cookieInput").value.trim(),mode:$("#modeSelect").value})});}await syncBackend();}catch(error){showToast(`连接请求失败：${error.message}`);}}
let toastTimer;function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),3000);}
function openSettings(){if(state.roomUrl&&!$("#roomInput").value)$("#roomInput").value=state.roomUrl;$("#settingsModal").classList.add("open");$("#settingsModal").setAttribute("aria-hidden","false");$("#roomInput").focus();}function closeSettings(){$("#settingsModal").classList.remove("open");$("#settingsModal").setAttribute("aria-hidden","true");}

$$('.feed-tab').forEach(button=>button.addEventListener("click",()=>{$$('.feed-tab').forEach(item=>{item.classList.remove("active");item.setAttribute("aria-selected","false");});button.classList.add("active");button.setAttribute("aria-selected","true");state.filter=button.dataset.filter;renderFeed();}));
$("#userSearch").addEventListener("input",event=>{state.search=event.target.value.trim();renderFeed();});
$("#rangeSelect").addEventListener("change",()=>{renderKeywords();showToast(`观察窗口：${$("#rangeSelect").selectedOptions[0].textContent}`);syncBackend();});
$("#connectButton").addEventListener("click",connectBackend);$("#resetButton").addEventListener("click",()=>{Object.assign(state,snapshotApi.resetViewState(state));renderAll();syncBackend();showToast("已同步当前会话");});$("#settingsButton").addEventListener("click",openSettings);$("#closeSettings").addEventListener("click",closeSettings);$("#cancelSettings").addEventListener("click",closeSettings);$("#settingsModal").addEventListener("click",event=>{if(event.target===$("#settingsModal"))closeSettings();});
$("#signalList").addEventListener("click",async event=>{const button=event.target.closest("[data-feedback]");if(!button)return;const card=button.closest("[data-signal-id]"),signalId=card?.dataset.signalId,note=card?.querySelector("[data-feedback-note]")?.value?.trim()||undefined;if(!signalId)return;try{await apiJson("/api/signals/feedback",{method:"POST",body:JSON.stringify({signal_id:signalId,feedback_type:button.dataset.feedback,note})});showToast("反馈已保存");}catch(error){showToast(`反馈保存失败：${error.message}`);}});
$("#saveSettings").addEventListener("click",()=>{if(!$("#roomInput").value.trim()){showToast("请填写 URL 或 room_id");return;}state.mode=$("#modeSelect").value;closeSettings();showToast("设置已保存 · 点击连接开始观察");});$("#toggleCookie").addEventListener("click",()=>{const input=$("#cookieInput");input.type=input.type==="password"?"text":"password";$("#toggleCookie").textContent=input.type==="password"?"显示":"隐藏";});document.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();$("#userSearch").focus();}if(event.key==="Escape")closeSettings();});
renderAll();syncBackend();setInterval(syncBackend,2000);
