const state={serverAvailable:false,connected:false,roomId:"",roomUrl:"",roomTitle:"待连接直播间",sessionId:null,runId:null,generation:0,workerAlive:false,dataSource:"none",asOf:null,lastValidAt:null,lastProtocolAt:null,protocolAvailable:"unknown",activityState:"unknown",protocolHealth:"unknown",freshness:null,coverage:{coverage_state:"unknown"},status:"idle",mode:"auto",filter:"all",search:"",events:[],metrics:null,lastError:""};
let capabilityToken="";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const typeNames={comment:"评论",like:"点赞",gift:"礼物",follow:"关注",share:"分享",viewer_change:"在线人数",entry:"进场",live_status:"状态"};
const snapshotApi=BulletScreenSnapshot;
const onboarding=BulletScreenOnboarding;
const launchOptions=onboarding.readLaunchOptions(window.location.href);
const formatNumber=n=>n===null||n===undefined||Number.isNaN(Number(n))?"—":new Intl.NumberFormat("zh-CN",{maximumFractionDigits:1}).format(n);
const percent=n=>n===null||n===undefined||Number.isNaN(Number(n))?"—":`${Math.round(Number(n)*100)}%`;
const escapeHtml=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
if(launchOptions.roomInput){if(/^\d+$/.test(launchOptions.roomInput))state.roomId=launchOptions.roomInput;else state.roomUrl=launchOptions.roomInput;}
if(launchOptions.demo)state.mode="demo";
function userStatusText(status,activityState,protocolAvailable){if(status==="connected"&&activityState==="quiet"&&protocolAvailable==="true")return "采集正常 · 最近暂无新互动";if(status==="connected"&&protocolAvailable==="false")return "直播页面已打开，但暂时没有获取到互动数据";if(status==="connected"&&protocolAvailable==="unknown")return "页面已打开 · 等待互动数据";if(status==="stale")return "采集可能中断";if(status==="stopping")return "正在停止";if(status==="connecting"||status==="starting")return "正在连接";if(status==="error")return "采集出错";if(status==="stopped")return "已停止";return status==="offline"?"服务离线":snapshotApi.statusText(status,activityState,protocolAvailable);}

function backendEventToFeed(item){const stamp=String(item.timestamp||item.event_time||"");const parsed=new Date(stamp);const time=Number.isNaN(parsed.getTime())?(stamp.slice(11,19)||"--:--:--"):parsed.toLocaleTimeString("zh-CN",{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"});return {time,user:item.user?.name||item.user_name||"匿名用户",type:item.type||item.event_type||"live_status",text:item.content||item.text||"",topic:item.topic||""};}
function currentWindow(){const selected=$("#rangeSelect")?.value||"60s";return state.metrics?.windows?.[selected]||state.metrics?.current||{};}
function renderFeed(){const list=$("#feedList"),query=state.search.toLowerCase();const filtered=state.events.filter(item=>(state.filter==="all"||item.type===state.filter)&&(!query||`${item.user} ${item.text}`.toLowerCase().includes(query)));list.innerHTML=filtered.length?filtered.slice(-160).reverse().map(item=>`<div class="feed-item"><span class="feed-time">[${escapeHtml(item.time)}]</span><div class="feed-main"><span class="feed-type ${escapeHtml(item.type)}">${escapeHtml(typeNames[item.type]||item.type)}</span><span class="feed-user">${escapeHtml(item.user)}：</span><span class="feed-text">${escapeHtml(item.text||"—")}</span></div></div>`).join(""):`<div class="empty-feed">没有匹配的事件<br><small>等待连接后的 protobuf 实时事件</small></div>`;$("#allCount").textContent=state.events.length;$("#eventRate").textContent=state.metrics?`${formatNumber(currentWindow().comment_rate)} 评论事件/分`:"—";}
function renderMetrics(){const current=currentWindow();const sentiment=state.metrics?.summary?.sentiment||{};const protocol=state.protocolAvailable==="true";const online=current.online??state.metrics?.online;$("#metricOnline").textContent=state.connected&&online!==null&&online!==undefined?`${protocol?"":"≈ "}${formatNumber(online)}`:"—";$("#metricCommentRate").textContent=state.connected?formatNumber(current.comment_rate):"—";$("#metricLikeRate").textContent=state.connected?formatNumber(current.like_rate):"—";$("#metricActive").textContent=state.connected?formatNumber(current.active_users):"—";$("#metricPurchase").textContent=state.connected?percent(current.purchase_ratio):"—";$("#metricSentiment").textContent=state.connected?`${percent(sentiment.positive)} / ${percent(sentiment.negative)}`:"—";$("#trendValue").innerHTML=state.connected?`${formatNumber(current.heat_score)} <small>观测热度</small>`:`— <small>等待连接</small>`;}
function renderAnalysis(){const metrics=state.metrics||{};const topics=metrics.topics||[];const questions=metrics.hot_questions||[];$("#topicList").innerHTML=topics.length?topics.map(item=>`<span class="analysis-chip">${escapeHtml(item.label)} <b>${item.count}</b></span>`).join(""):`<span class="muted">连接后生成</span>`;$("#questionList").innerHTML=questions.length?questions.map(item=>`<div class="question-row"><span>${escapeHtml(item.question)}</span><b>${item.count}</b></div>`).join(""):`<div class="muted">等待评论事件</div>`;const sentiment=metrics.summary?.sentiment||{};const positive=sentiment.positive===null||sentiment.positive===undefined||Number.isNaN(Number(sentiment.positive))?null:Number(sentiment.positive),negative=sentiment.negative===null||sentiment.negative===undefined||Number.isNaN(Number(sentiment.negative))?null:Number(sentiment.negative),neutral=positive===null||negative===null?null:Math.max(0,1-positive-negative);$("#positiveBar").style.width=positive===null?"0%":`${positive*100}%`;$("#neutralBar").style.width=neutral===null?"0%":`${neutral*100}%`;$("#negativeBar").style.width=negative===null?"0%":`${negative*100}%`;$("#sentimentLabel").textContent=state.connected?(positive===null||negative===null?"正 — · 中 — · 负 —":`正 ${percent(positive)} · 中 ${percent(neutral)} · 负 ${percent(negative)}`):"—";}
function renderSignals(){const signals=state.metrics?.signals||[],list=$("#signalList"),open=new Set([...list.querySelectorAll("details[open]")].map(item=>item.closest("[data-signal-id]")?.dataset.signalId));$("#signalCount").textContent=signals.length?`${signals.length} 条`:state.sessionId?"0 条":"—";list.innerHTML=signals.length?signals.map(BulletScreenSignals.renderCard).join(""):`<div class="empty-state"><span class="empty-orb">◎</span><p>${escapeHtml(BulletScreenSignals.emptyText({started:!!state.sessionId,coverageState:state.coverage?.coverage_state||"unknown",demo:state.mode==="demo"}))}</p></div>`;for(const card of list.querySelectorAll("[data-signal-id]")){if(open.has(card.dataset.signalId))card.querySelector("details")?.setAttribute("open","");}}
function renderKeywords(){const metrics=state.metrics||{},keywords=metrics.keywords||[];const max=Math.max(...keywords.map(item=>Number(item[1])||0),1);$("#keywordList").innerHTML=keywords.length?keywords.map(item=>`<div class="keyword-row" style="--bar:${Math.max(15,(Number(item[1])||0)/max*100)}%"><span>${escapeHtml(item[0])}</span><span class="keyword-count">${item[1]}</span></div>`).join(""):`<div class="empty-feed">连接后显示评论热词</div>`;const current=currentWindow();$("#miniStats").innerHTML=`<span>礼物事件 / 分 <b>${formatNumber(current.gift_rate)}</b></span><span>分享事件（当前范围） <b>${formatNumber(current.shares)}</b></span><span>观测热度 <b>${formatNumber(current.heat_score)}</b></span>`;}
function createPath(points,width,height,padding=22){const known=points.map((point,index)=>[point,index]).filter(([point])=>Number.isFinite(point));if(known.length<2)return "";const max=Math.max(...known.map(item=>item[0])),min=Math.min(...known.map(item=>item[0])),range=max-min||1;return known.map(([point,index],pathIndex)=>{const x=padding+index*((width-padding*2)/(points.length-1));const y=height-padding-((point-min)/range)*(height-padding*2);return `${pathIndex?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`;}).join(" ");}
function renderChart(){const svg=$("#trendChart"),points=state.metrics?.trend||[],width=720,height=210,grid=[35,75,115,155,195].map(y=>`<line class="chart-gridline" x1="22" y1="${y}" x2="698" y2="${y}"/>`).join("");if(points.length<2){svg.innerHTML=`${grid}<text x="360" y="112" text-anchor="middle" fill="#9095a1" font-size="12">连接后生成真实趋势</text>`;$("#chartAxis").innerHTML="<span>—</span><span>—</span><span>—</span><span>等待数据</span>";return;}const online=points.map(point=>point.online===null||point.online===undefined?null:Number(point.online)),comments=points.map(point=>point.comment_rate===null||point.comment_rate===undefined||Number.isNaN(Number(point.comment_rate))?null:Number(point.comment_rate)),onlinePath=createPath(online,width,height),commentPath=createPath(comments,width,height),areaPath=onlinePath?`${onlinePath} L698,${height-10} L22,${height-10} Z`:"";svg.innerHTML=`<defs><linearGradient id="trendFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#4c9ae8" stop-opacity=".28"/><stop offset="1" stop-color="#4c9ae8" stop-opacity=".03"/></linearGradient></defs>${grid}${areaPath?`<path class="chart-area" d="${areaPath}"/>`:""}${onlinePath?`<path class="chart-online" d="${onlinePath}"/>`:""}${commentPath?`<path class="chart-danmaku" d="${commentPath}"/>`:""}`;const times=points.map(point=>String(point.recorded_at||"").slice(11,16)||"—");$("#chartAxis").innerHTML=[times[0],times[Math.floor(times.length/2)],times[times.length-1],"现在"].map(label=>`<span>${escapeHtml(label)}</span>`).join("");}
function renderConnection(){const status=state.serverAvailable?state.status:"offline";const statusLabel=userStatusText(status,state.activityState,state.protocolAvailable);$("#roomIdLabel").textContent=state.mode==="demo"?"演示":state.roomId?`# ${state.roomId}`:"—";$("#roomTitle").textContent=state.mode==="demo"?"演示直播间 · 不是真实直播":state.roomTitle;$("#modeBadge").textContent=state.mode==="demo"?"演示数据 · 不是真实直播":state.protocolAvailable==="true"?"实时互动可用":state.protocolAvailable==="false"?"暂时没有互动数据":state.serverAvailable?"页面已打开":"服务离线";$("#connectButton").classList.toggle("connected",state.connected);$("#connectButton").classList.toggle("disconnected",!state.connected);$("#connectLabel").textContent=statusLabel;$("#feedState").classList.toggle("paused",!state.connected);$("#feedState").innerHTML=`<span class="pulse-dot"></span>${statusLabel}`;const identity=state.sessionId?`当前会话 · ${String(state.runId||"").slice(0,8)}`:`还没有开始采集`;$("#feedFooterText").textContent=state.lastError?`${statusLabel}：${state.lastError}`:`${identity} · ${snapshotApi.coverageText(state.coverage)}`;$("#feedFooterText").title=state.asOf?`数据截至 ${state.asOf}`:"";$("#dashboardFootText").textContent=state.lastError||`数据截至：${state.asOf||"—"}`;$("#storageModeLabel").innerHTML=state.mode==="demo"?"<b>● 演示数据</b> 演示内容只在运行期间保留，不写入本机文件":"<b class=\"green-label\">● 本地保存</b> 事件与指标只写入本机 SQLite";}
function reliableIdentity(){return [state.roomId,state.sessionId,state.runId,state.generation].join("|");}
function prepareLastReliable(){const key=reliableIdentity();if(state.lastIdentityKey!==undefined&&state.lastIdentityKey!==key)state.lastReliable=null;state.lastIdentityKey=key;const healthy=state.connected&&!!state.sessionId&&state.protocolAvailable==="true"&&state.protocolHealth==="healthy"&&!!state.lastProtocolAt;if(healthy)state.lastReliable={key,lastValidAt:state.lastValidAt,metrics:state.metrics,events:state.events};const failed=state.snapshotFailed||["stale","error","offline"].includes(state.status);if(failed&&state.lastReliable?.key===key){state.metrics=state.lastReliable.metrics;state.events=state.lastReliable.events;if(!state.lastValidAt)state.lastValidAt=state.lastReliable.lastValidAt;}}
const truthActionLabels={retry:"重新检查",connect:"重新连接",settings:"修改直播间",login:"检查登录状态",demo:"先试 Demo"};
function renderTruthPanel(){if(state.snapshotFailed&&!state.persistentError)state.persistentError={code:state.errorCode||"api_error",message:state.lastError||"本地服务没有响应",sticky:false};else if(!state.snapshotFailed&&state.persistentError&&!state.persistentError.sticky)state.persistentError=null;const failure=state.persistentError,model=snapshotApi.dashboardPresentation({provider:"douyin",serverAvailable:state.serverAvailable,status:failure?"error":state.status,activityState:state.activityState,protocolAvailable:state.protocolAvailable,protocolHealth:state.protocolHealth,coverage:state.coverage,roomTitle:state.roomTitle,roomId:state.mode==="demo"?"演示":state.roomId,window:$("#rangeSelect").value,asOf:state.asOf,lastValidAt:state.lastValidAt,dataSource:state.dataSource,sessionId:state.sessionId,runId:state.runId,generation:state.generation,error:failure?.message||state.lastError,errorCode:failure?.code,snapshotFailed:state.snapshotFailed,mode:state.mode});$("#truthHeadline").textContent=model.headline;$("#truthGuidance").textContent=model.guidance;$("#truthPlatform").textContent=model.platformLabel;$("#truthRoom").textContent=model.roomLabel;$("#truthWindow").textContent=model.windowLabel;$("#truthCoverage").textContent=model.coverageLabel;$("#truthAsOf").textContent=model.asOfLabel;const last=$("#lastReliableLabel");last.textContent=model.lastReliableLabel;last.classList.toggle("hidden",!model.lastReliableLabel);const tone=/采集正常|演示数据正在运行/.test(model.headline)?"good":/缺口|中断|无法|不可用|出错|错误|离线/.test(model.headline)?"warning":"neutral";$("#truthPanel").dataset.tone=tone;$("#truthActions").innerHTML=model.actions.map(action=>`<button type="button" data-truth-action="${action}">${truthActionLabels[action]}</button>`).join("");$("#diagnosticStatus").textContent=model.diagnostics.status;$("#diagnosticSource").textContent=model.diagnostics.dataSource;$("#diagnosticProtocolHealth").textContent=model.diagnostics.protocolHealth;$("#diagnosticProtocolAvailable").textContent=model.diagnostics.protocolAvailable;$("#diagnosticSession").textContent=model.diagnostics.sessionId;$("#diagnosticRun").textContent=model.diagnostics.runId;$("#diagnosticGeneration").textContent=model.diagnostics.generation;$("#diagnosticError").textContent=model.diagnostics.error;$("#metricFreshnessNote").classList.toggle("hidden",!state.lastReliable||!(["stale","error","offline"].includes(state.status)||state.snapshotFailed));$("#feedFooterText").textContent=model.guidance;$("#feedFooterText").title=model.lastReliableLabel||"";$("#dashboardFootText").textContent=model.guidance;$("#snapshotLabel").textContent=model.snapshotLabel;}
function renderFeedTruthfulEmpty(){if(state.events.length)return;const empty=$("#feedList .empty-feed");if(!empty)return;const model=snapshotApi.dashboardPresentation({provider:"douyin",serverAvailable:state.serverAvailable,status:state.status,protocolAvailable:state.protocolAvailable,protocolHealth:state.protocolHealth,activityState:state.activityState,coverage:state.coverage,mode:state.mode});empty.textContent=model.headline==="采集正常 · 最近暂无新互动"?model.headline:model.headline==="存在采集缺口"?"这段时间存在采集缺口，不能据此判断没有互动。":model.headline==="暂时无法判断数据是否完整"?"暂时无法判断这段时间是否有互动。":model.headline==="采集可能中断"?"采集可能中断；请查看上方恢复提示。":model.headline==="已停止"||model.headline==="尚未开始采集"?"尚未开始采集。选择房间并连接后，这里会显示实时互动。":model.headline;}
function renderRetainedMetrics(){if(!state.lastReliable||!(state.snapshotFailed||["stale","error","offline"].includes(state.status)))return;const metrics=state.lastReliable.metrics||{},window=metrics.windows?.[$("#rangeSelect").value]||metrics.current||{},sentiment=metrics.summary?.sentiment||{},online=window.online??metrics.online;$("#metricOnline").textContent=online===null||online===undefined?"—":formatNumber(online);$("#metricCommentRate").textContent=formatNumber(window.comment_rate);$("#metricLikeRate").textContent=formatNumber(window.like_rate);$("#metricActive").textContent=formatNumber(window.active_users);$("#metricPurchase").textContent=percent(window.purchase_ratio);$("#metricSentiment").textContent=`${percent(sentiment.positive)} / ${percent(sentiment.negative)}`;$("#trendValue").innerHTML=`${formatNumber(window.heat_score)} <small>最后可靠值</small>`;}
function syncStatusHeader(){const label=$("#truthHeadline").textContent,confirmed=["采集正常","采集正常 · 最近暂无新互动","演示数据正在运行"].includes(label);$("#connectLabel").textContent=label;$("#connectButton").classList.toggle("connected",confirmed);$("#connectButton").classList.toggle("disconnected",!confirmed);$("#connectButton").disabled=label==="正在停止";$("#feedState").classList.toggle("paused",!confirmed);$("#feedState").innerHTML=`<span class="pulse-dot"></span>${escapeHtml(label)}`;}
function renderAll(){prepareLastReliable();renderConnection();renderFeed();renderMetrics();renderAnalysis();renderSignals();renderKeywords();renderChart();renderRetainedMetrics();renderFeedTruthfulEmpty();renderTruthPanel();syncStatusHeader();}
async function loadCapability(){const response=await fetch("/api/bootstrap",{headers:{"Accept":"application/json"}});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.token)throw new Error(payload.error||"本地服务未提供会话令牌");capabilityToken=payload.token;return capabilityToken;}
async function apiJson(path,options={},retry=true){if(path!=="/api/bootstrap"&&!capabilityToken)await loadCapability();const headers={"Content-Type":"application/json",...(options.headers||{}),...(capabilityToken?{"X-Bullet-Screen-Token":capabilityToken}:{})};const response=await fetch(path,{...options,headers});const payload=await response.json().catch(()=>({}));if(response.status===401&&retry){capabilityToken="";await loadCapability();return apiJson(path,options,false);}if(!response.ok)throw new Error(payload.error||`本地服务 HTTP ${response.status}`);return payload;}
let snapshotClient;
snapshotClient=new snapshotApi.SnapshotClient(({signal,requestGeneration})=>{const window=$("#rangeSelect")?.value||"60s";return apiJson(`/api/snapshot?window=${encodeURIComponent(window)}&limit=300`,{signal,headers:{"X-Bullet-Screen-Request-Generation":String(requestGeneration)}});},snapshot=>{const next=snapshotApi.applySnapshotState(state,snapshot),metrics=snapshot.metrics||{};Object.assign(state,next,{serverAvailable:true,status:snapshot.status||"idle",roomUrl:state.roomUrl,mode:metrics.adapter_mode||state.mode,events:(snapshot.events?.items||[]).map(backendEventToFeed)});renderAll();},error=>{const wasAvailable=state.serverAvailable;Object.assign(state,snapshotApi.clearSnapshotState(state,error.message),{serverAvailable:wasAvailable,status:wasAvailable?"error":"offline",dataSource:"none"});if(wasAvailable)showToast(`本地服务异常：${error.message}`);renderAll();});
async function syncBackend(){return snapshotClient.refresh();}
async function connectBackend(){state.persistentError=null;try{if(!state.serverAvailable)await syncBackend();if(!state.serverAvailable){state.persistentError={code:"api_error",message:"本地服务没有响应，请启动 Bullet-Screen 或运行安装环境检查。",sticky:false};renderAll();return;}if(state.connected){await apiJson("/api/disconnect",{method:"POST",body:"{}"});}else{const mode=$("#modeSelect").value,input=$("#roomInput").value.trim(),normalized=onboarding.normalizeRoomInput(input);if(mode!=="demo"&&!normalized){state.persistentError={code:"room_invalid",message:"请输入直播间链接或房间号。",sticky:true};renderAll();openSettings();return;}const demoRoom="123456",effective=mode==="demo"?demoRoom:normalized,isId=effective&&/^\d+$/.test(effective);state.status="connecting";renderAll();await apiJson("/api/connect",{method:"POST",body:JSON.stringify({room_id:isId?effective:"",url:isId?"":(effective||""),cookie:$("#cookieInput").value.trim(),mode})});}state.persistentError=null;await syncBackend();}catch(error){state.status="error";state.persistentError={code:"connect_error",message:error.message,sticky:true};showToast(`连接请求失败：${error.message}`);renderAll();}}
let toastTimer;function showToast(message){const toast=$("#toast");toast.textContent=snapshotApi.userFacingError(message,"本地服务暂时无法响应，请重新检查。");toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),3000);}
function openSettings(){if(!$("#roomInput").value)$("#roomInput").value=state.roomUrl||state.roomId||"";$("#settingsModal").classList.add("open");$("#settingsModal").setAttribute("aria-hidden","false");$("#roomInput").focus();}function closeSettings(){$("#settingsModal").classList.remove("open");$("#settingsModal").setAttribute("aria-hidden","true");}

$$('.feed-tab').forEach(button=>button.addEventListener("click",()=>{$$('.feed-tab').forEach(item=>{item.classList.remove("active");item.setAttribute("aria-selected","false");});button.classList.add("active");button.setAttribute("aria-selected","true");state.filter=button.dataset.filter;renderFeed();}));
$("#userSearch").addEventListener("input",event=>{state.search=event.target.value.trim();renderFeed();});
$("#rangeSelect").addEventListener("change",()=>{renderAll();showToast(`观察窗口：${$("#rangeSelect").selectedOptions[0].textContent}`);syncBackend();});
$("#connectButton").addEventListener("click",connectBackend);$("#resetButton").addEventListener("click",()=>{Object.assign(state,snapshotApi.resetViewState(state));renderAll();syncBackend();showToast("已同步当前会话");});$("#settingsButton").addEventListener("click",openSettings);$("#closeSettings").addEventListener("click",closeSettings);$("#cancelSettings").addEventListener("click",closeSettings);$("#settingsModal").addEventListener("click",event=>{if(event.target===$("#settingsModal"))closeSettings();});
$("#signalList").addEventListener("click",async event=>{const button=event.target.closest("[data-feedback]");if(!button)return;const card=button.closest("[data-signal-id]"),signalId=card?.dataset.signalId,note=card?.querySelector("[data-feedback-note]")?.value?.trim()||undefined;if(!signalId)return;try{await apiJson("/api/signals/feedback",{method:"POST",body:JSON.stringify({signal_id:signalId,feedback_type:button.dataset.feedback,note})});showToast("反馈已保存");}catch(error){showToast(`反馈保存失败：${error.message}`);}});
$("#saveSettings").addEventListener("click",()=>{const mode=$("#modeSelect").value,raw=$("#roomInput").value.trim(),normalized=onboarding.normalizeRoomInput(raw);if(mode!=="demo"&&!normalized){showToast("请输入直播间链接或房间号。");return;}state.mode=mode;if(normalized){if(/^\d+$/.test(normalized)){state.roomId=normalized;state.roomUrl="";}else{state.roomUrl=normalized;state.roomId="";}}closeSettings();showToast(mode==="demo"?"演示设置已保存 · 这是演示数据，不是真实直播":"设置已保存 · 点击连接开始采集");});$("#toggleCookie").addEventListener("click",()=>{const input=$("#cookieInput");input.type=input.type==="password"?"text":"password";$("#toggleCookie").textContent=input.type==="password"?"显示":"隐藏";});document.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();$("#userSearch").focus();}if(event.key==="Escape")closeSettings();});
$("#truthActions").addEventListener("click",event=>{const action=event.target.closest("[data-truth-action]")?.dataset.truthAction;if(action==="retry")syncBackend();else if(action==="connect")connectBackend();else if(action==="settings")openSettings();else if(action==="login"){openSettings();$("#cookieInput").focus();}else if(action==="demo"){$("#modeSelect").value="demo";state.mode="demo";connectBackend();}});
$("#saveSettings").addEventListener("click",()=>{const mode=$("#modeSelect").value;if(mode!=="demo"&&!onboarding.normalizeRoomInput($("#roomInput").value.trim())){state.persistentError={code:"room_invalid",message:"请输入直播间链接或房间号。",sticky:true};closeSettings();renderAll();return;}state.persistentError=null;});$("#roomInput").addEventListener("input",()=>{if(state.persistentError?.code==="room_invalid")state.persistentError=null;});
if(launchOptions.demo)$("#modeSelect").value="demo";renderAll();syncBackend().then(()=>{if(launchOptions.demo&&launchOptions.autostart&&!state.connected)connectBackend();});setInterval(syncBackend,2000);
