const state={connected:false,serverAvailable:false,connectionStatus:"idle",dataSource:"none",roomId:"7734200",activeRoomId:"",roomTitle:"待连接直播间",filter:"all",search:"",messages:[],ranking:[],keywords:[],trend:[],lastError:"",likes:0,peak:null,rate:0,total:0,revenue:null,sessdata:""};
let capabilityToken="";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], typeNames={danmaku:"弹幕",gift:"礼物",sc:"SC",entry:"进场",interact:"互动"};
const formatNumber=n=>new Intl.NumberFormat("zh-CN").format(n);
const escapeHtml=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const formatLocalClock=(value,seconds=true)=>{const date=new Date(value);if(Number.isNaN(date.getTime()))return "--:--:--";return new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",second:seconds?"2-digit":undefined,hour12:false}).format(date);};
function clearLiveData(){state.messages=[];state.likes=0;state.peak=null;state.rate=0;state.total=0;state.revenue=null;state.ranking=[];state.keywords=[];state.trend=[];}

function renderFeed(){const list=$("#feedList");const filtered=state.messages.filter(item=>(state.filter==="all"||item.type===state.filter)&&(!state.search||`${item.user} ${item.text}`.toLowerCase().includes(state.search.toLowerCase())));const emptyText=!state.connected?"尚未连接 B 站实时数据<br><small>不会显示 SQLite 历史记录</small>":state.messages.length?"没有匹配的消息<br><small>试试清除筛选条件</small>":"已连接，等待实时消息";list.innerHTML=filtered.length?filtered.map(item=>`<div class="feed-item"><span class="feed-time">[${escapeHtml(item.time)}]</span><div class="feed-main"><span class="feed-type ${item.type}">${typeNames[item.type]}</span><span class="feed-user">${escapeHtml(item.user)}：</span><span class="feed-text">${escapeHtml(item.text)}</span></div></div>`).join(""):`<div class="empty-feed">${emptyText}</div>`;$("#allCount").textContent=state.messages.length;$("#eventRate").textContent=state.connected?`${state.rate} 条/分`:"—";}
function renderMetrics(){const revenue=state.revenue===null||state.revenue===undefined?"—":`¥${state.revenue}`;$("#metricPeak").textContent=state.connected&&state.peak!==null&&state.peak!==undefined?formatNumber(state.peak):"—";$("#metricLikes").textContent=state.connected?formatNumber(state.likes):"—";$("#metricRate").textContent=state.connected?state.rate:"—";$("#metricDanmaku").textContent=state.connected?formatNumber(state.total):"—";$("#metricRevenue").textContent=state.connected?revenue:"—";$("#giftTotal").textContent=state.connected?revenue:"—";$("#scCount").textContent=state.messages.filter(item=>item.type==="sc").length;$("#giftCount").textContent=state.messages.filter(item=>item.type==="gift").length;$("#trendValue").innerHTML=state.connected?`${state.rate} <small>条 / 分</small>`:`— <small>等待连接</small>`;}
function renderRanking(){const max=Math.max(...state.ranking.map(i=>i[1]),1);$("#rankingList").innerHTML=state.ranking.length?state.ranking.slice(0,10).map(([name,count])=>`<li class="rank-row" style="--bar:${Math.max(24,count/max*100)}%"><span class="rank-user">${escapeHtml(name)}</span><span class="rank-count">${count} 条</span></li>`).join(""):`<li class="empty-feed">连接后显示真实榜单</li>`;}
function renderKeywords(){const max=Math.max(...state.keywords.map(i=>i[1]),1);$("#keywordList").innerHTML=state.keywords.length?state.keywords.map(([word,count])=>`<div class="keyword-row" style="--bar:${Math.max(15,count/max*100)}%"><span>${escapeHtml(word)}</span><span class="keyword-count">${count}</span></div>`).join(""):`<div class="empty-feed">连接后显示真实热词</div>`;}
function createPath(points,width,height,padding=10){const known=points.map((point,index)=>[point,index]).filter(([point])=>Number.isFinite(point));if(known.length<2)return "";const max=Math.max(...known.map(item=>item[0])),min=Math.min(...known.map(item=>item[0])),range=max-min||1;return known.map(([point,index],pathIndex)=>{const x=padding+index*((width-padding*2)/(points.length-1));const y=height-padding-((point-min)/range)*(height-padding*2);return `${pathIndex?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`;}).join(" ");}
function renderChart(){const svg=$("#trendChart"),points=state.trend||[],width=720,height=210,grid=[35,75,115,155,195].map(y=>`<line class="chart-gridline" x1="22" y1="${y}" x2="698" y2="${y}"/>`).join("");if(points.length<2){svg.innerHTML=`${grid}<text x="360" y="112" text-anchor="middle" fill="#9095a1" font-size="12">连接后生成真实趋势</text>`;$(".chart-axis").innerHTML="<span>—</span><span>—</span><span>—</span><span>等待数据</span>";return;}const online=points.map(point=>point.online===null||point.online===undefined?null:Number(point.online)),danmaku=points.map(point=>Number.isFinite(Number(point.danmaku_rate))?Number(point.danmaku_rate):null),onlinePath=createPath(online,width,height,22),danmakuPath=createPath(danmaku,width,height,22),areaPath=onlinePath?`${onlinePath} L698,${height-10} L22,${height-10} Z`:"",knownDanmaku=danmaku.map((value,index)=>[value,index]).filter(([value])=>Number.isFinite(value)),lastPoint=knownDanmaku.length?knownDanmaku[knownDanmaku.length-1]:null,danmakuMin=knownDanmaku.length?Math.min(...knownDanmaku.map(item=>item[0])):0,danmakuRange=knownDanmaku.length?Math.max(...knownDanmaku.map(item=>item[0]))-danmakuMin||1:1,lastX=lastPoint?22+lastPoint[1]*((width-44)/(points.length-1)):22,lastY=lastPoint?height-22-((lastPoint[0]-danmakuMin)/danmakuRange)*(height-44):height-22;svg.innerHTML=`<defs><linearGradient id="trendFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#4c9ae8" stop-opacity=".28"/><stop offset="1" stop-color="#4c9ae8" stop-opacity=".03"/></linearGradient></defs>${grid}${areaPath?`<path class="chart-area" d="${areaPath}"/>`:""}${onlinePath?`<path class="chart-online" d="${onlinePath}"/>`:""}${danmakuPath?`<path class="chart-danmaku" d="${danmakuPath}"/>`:""}${lastPoint?`<circle class="chart-point" cx="${lastX}" cy="${lastY}" r="4"/>`:""}`;const times=points.map(point=>formatLocalClock(point.recorded_at,false)),axis=[times[0],times[Math.floor(times.length/2)],times[times.length-1],"现在"];$(".chart-axis").innerHTML=axis.map(label=>`<span>${escapeHtml(label)}</span>`).join("");}
function renderConnection(){const displayedRoomId=state.activeRoomId||state.roomId;$("#roomIdLabel").textContent=`# ${displayedRoomId}`;$("#roomTitle").textContent=state.roomTitle;$("#connectButton").classList.toggle("connected",state.connected);$("#connectButton").classList.toggle("disconnected",!state.connected);$("#connectLabel").textContent=!state.serverAvailable?"服务离线":state.connected?"已连接":"连接";$("#dataSourceLabel").textContent=state.connected&&state.dataSource==="bilibili_websocket"?"B站实时 WebSocket":["connecting","authenticating"].includes(state.connectionStatus)?"正在验证 B站连接":"本地服务 · 无实时数据";$("#feedState").classList.toggle("paused",!state.connected);$("#feedState").innerHTML=state.connected?`<span class="pulse-dot"></span>收流中`:`<span class="pulse-dot"></span>未连接`;$("#feedFooterText").textContent=state.lastError?`连接失败：${state.lastError}`:state.connected?"实时刷新 · 当前会话":state.serverAvailable?"未连接 · 不显示历史数据":"启动本地服务后连接";$("#feedFooterText").title=state.lastError;}
function renderAll(){renderConnection();renderFeed();renderMetrics();renderRanking();renderKeywords();renderChart();}
async function loadCapability(){const response=await fetch("/api/bootstrap",{headers:{"Accept":"application/json"}});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.token)throw new Error(payload.error||"本地服务未提供会话令牌");capabilityToken=payload.token;return capabilityToken;}
async function apiJson(path,options={},retry=true){if(path!=="/api/bootstrap"&&!capabilityToken)await loadCapability();const headers={"Content-Type":"application/json",...(options.headers||{}),...(capabilityToken?{"X-Bullet-Screen-Token":capabilityToken}:{})};const response=await fetch(path,{...options,headers});const payload=await response.json().catch(()=>({}));if(response.status===401&&retry){capabilityToken="";await loadCapability();return apiJson(path,options,false);}if(!response.ok)throw new Error(payload.error||`本地服务 HTTP ${response.status}`);return payload;}
function backendEventToFeed(item){return {time:formatLocalClock(item.event_time),user:item.uname||"匿名用户",type:item.event_type||"unknown",text:item.text||item.gift_name||(item.event_type==="online"?`热度 ${item.popularity||0}`:item.event_type==="like"?"点赞":"")};}
async function syncBackend(){try{const status=await apiJson("/api/status");state.serverAvailable=true;state.connected=!!status.connected;state.connectionStatus=status.status||"idle";state.dataSource=status.data_source||"none";state.lastError=status.last_error||"";const hasActiveRoom=["connecting","authenticating","connected"].includes(state.connectionStatus);state.activeRoomId=hasActiveRoom&&status.room_id?status.room_id:"";if(hasActiveRoom&&status.room_title)state.roomTitle=status.room_title;if(state.connected&&status.session_id&&state.dataSource==="bilibili_websocket"){const [metrics,events]=await Promise.all([apiJson("/api/metrics"),apiJson("/api/events?limit=200")]);const verified=metrics.connected&&metrics.session_id===status.session_id&&events.session_id===status.session_id&&events.data_source==="bilibili_websocket";if(verified){state.messages=(events.events||[]).map(backendEventToFeed);state.likes=metrics.likes||0;state.peak=metrics.online??null;state.rate=metrics.rate||0;state.total=metrics.total||0;state.revenue=metrics.revenue??null;state.ranking=metrics.ranking||[];state.keywords=metrics.keywords||[];state.trend=metrics.trend||[];}else{clearLiveData();}}else{clearLiveData();}renderAll();$("#snapshotLabel").textContent=status.connected?"B站实时数据":status.status==="error"?"连接失败":["connecting","authenticating"].includes(status.status)?"正在验证连接":"等待连接";}catch(error){if(state.serverAvailable)showToast(`本地服务异常：${error.message}`);state.serverAvailable=false;state.connected=false;state.connectionStatus="offline";state.dataSource="none";state.activeRoomId="";state.lastError="本地服务不可用";clearLiveData();renderAll();}}
async function connectBackend(){try{if(!state.serverAvailable)await syncBackend();if(!state.serverAvailable){showToast("本地服务未启动：请运行 python3 server.py");return;}if(state.connected)await apiJson("/api/disconnect",{method:"POST",body:"{}"});else await apiJson("/api/connect",{method:"POST",body:JSON.stringify({room_id:state.roomId,sessdata:state.sessdata||$("#cookieInput").value.trim()})});await syncBackend();}catch(error){showToast(`连接请求失败：${error.message}`);}}
let toastTimer;function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2600);}
function resetLocalState(){state.roomId="7734200";state.activeRoomId="";state.roomTitle="待连接直播间";state.filter="all";state.search="";$("#userSearch").value="";$("#rangeSelect").value="live";$$('.feed-tab').forEach(item=>{item.classList.toggle("active",item.dataset.filter==="all");item.setAttribute("aria-selected",String(item.dataset.filter==="all"));});if(state.serverAvailable){syncBackend();showToast("已向本地服务同步当前实时会话");return;}state.connected=false;state.connectionStatus="offline";state.dataSource="none";state.lastError="";clearLiveData();renderAll();showToast("已清空本地看板状态");}
function openSettings(){$("#roomInput").value=state.roomId;$("#settingsModal").classList.add("open");$("#settingsModal").setAttribute("aria-hidden","false");$("#roomInput").focus();}function closeSettings(){$("#settingsModal").classList.remove("open");$("#settingsModal").setAttribute("aria-hidden","true");}

$$('.feed-tab').forEach(button=>button.addEventListener("click",()=>{$$('.feed-tab').forEach(item=>{item.classList.remove("active");item.setAttribute("aria-selected","false");});button.classList.add("active");button.setAttribute("aria-selected","true");state.filter=button.dataset.filter;renderFeed();}));
$("#userSearch").addEventListener("input",event=>{state.search=event.target.value.trim();renderFeed();});
$("#rangeSelect").addEventListener("change",event=>{const label=event.target.options[event.target.selectedIndex].textContent;$("#snapshotLabel").textContent=`已切换 · ${label}`;showToast(`看板时间范围：${label}`);});
$("#connectButton").addEventListener("click",connectBackend);
$("#resetButton").addEventListener("click",resetLocalState);$("#settingsButton").addEventListener("click",openSettings);$("#storageButton").addEventListener("click",()=>showToast("仅真实 WebSocket 会话写入 SQLite；未连接时看板保持空白"));$("#closeSettings").addEventListener("click",closeSettings);$("#cancelSettings").addEventListener("click",closeSettings);$("#settingsModal").addEventListener("click",event=>{if(event.target===$("#settingsModal"))closeSettings();});
$("#saveSettings").addEventListener("click",()=>{const newRoom=$("#roomInput").value.trim()||"7734200";if(!/^\d+$/.test(newRoom)){showToast("房间号必须是数字");return;}state.roomId=newRoom;if(!state.connected){state.activeRoomId="";state.roomTitle=`待连接直播间 · ${newRoom}`;}state.sessdata=$("#cookieInput").value.trim();closeSettings();renderConnection();showToast(state.connected?`房间 ${newRoom} 已保存 · 请先断开再重新连接`:`设置已保存 · 点击连接开始采集`);});
$("#toggleCookie").addEventListener("click",()=>{const input=$("#cookieInput");input.type=input.type==="password"?"text":"password";$("#toggleCookie").textContent=input.type==="password"?"显示":"隐藏";});
$$('[data-action]').forEach(button=>button.addEventListener("click",()=>{if(button.dataset.action==="gift"){showToast("礼物明细将在收到礼物后显示");return;}state.keywords=state.keywords.filter(([word])=>!["全部","主要"].includes(word));renderKeywords();showToast("已清除 2 个停用词");}));
document.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();$("#userSearch").focus();}if(event.key==="Escape")closeSettings();});
renderAll();syncBackend();setInterval(syncBackend,2000);setInterval(()=>{if(state.connected)$("#snapshotLabel").textContent=`更新于 ${new Date().toTimeString().slice(0,8)}`;},30000);
